<h2>FAQ</h2>
<?php echo $this->siteSubMenu('FAQ', new Admin_Model_DbTable_AdminMenu(), 'name') ?>
<h3>Select category:</h2>
<?php echo $this->renderTree(new ZfBlank_DbTable_Categories(array('name'=>'FAQCategories')), 'dom',
    array(
        'valueSource' => new ZfBlank_ActiveRow_FieldDecorator(array('fieldName' => 'name')),
        'valueContainer' => array('a', 'attributes' => array(
            'href' => new ZfBlank_ActiveRow_FieldDecorator(array(
                'prefix' => '/admin/faq/category/id/',
                'fieldName'=>'id',
            ))
        ))
    ))->saveHTML();
?>
    

