<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headMeta()
	->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');?>
<?php echo $this->headLink()
	->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/flora/jquery-ui.css')
	->appendStylesheet('/dropdown-menu/dropdown-menu-base.css')
	->appendStylesheet('/style.css')
?>
<?php echo $this->headScript()
	->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.js')
	->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8.16/jquery-ui.js')
	->appendFile('/dropdown-menu/dropdown-menu.js')
?>
</head>
<body>
    <h1>ZF_Blanks</h1>
	<div id="siteMenu">
		<?php echo $this->siteMenu() ?>
	</div>
	<script type="text/javascript">
		$(function() {
			$("div#siteMenu").initMenu();
		});
	</script> 
	<?php echo $this->layout()->content; ?>
    <hr>
    <div id="hosting">The project is hosted by
        <a href="http://developer.berlios.de">
            <img src="http://developer.berlios.de/bslogo.php?group_id=12682" width="83" height="21" border="0" alt="BerliOS Logo" />
        </a>
    </div>
    <div id="copyright">
        <address>Copyright &copy; 2011-2013 <a href="http://wooden.byethost32.com">Serge V. Baumer</a></address>
    </div>
</body>
